<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_multifileuploader"
 *
 * Auto generated by Extension Builder 2016-05-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PITS Multi File Uploader',
	'description' => 'An extension to upload multiple files at the same time with the feature to customize number of files, type of files, size of file etc. It has the feature to add new uploader or interchange the single file uploader in a form with multiple form uploader.',
	'category' => 'plugin',
	'author' => 'Akhil Jayan',
	'author_email' => 'akhil.jn@pitsolutions.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'php' => '5.3.0-6.0.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
